import ThemeContext from "@/context/ThemeContext";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SessionContext from "@/context/SessionContext";
import Navigation from "./(site)/MainComponents/Navigation";
import MainFooter from "./(site)/MainComponents/MainFooter";
import { Toaster } from "@/components/ui/toaster";

const lato = Inter({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={lato.className}>
      <body>
        <SessionContext>
          {children}
          <Toaster />
        </SessionContext>
      </body>
    </html>
  );
}
