import { Toaster } from "@/components/ui/toaster";
import CartProvider from "@/context/CartProvider";
import SessionContext from "@/context/SessionContext";
import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/context/StoreProviders";

const lato = Inter({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={lato.className}>
      <body>
        <SessionContext>
          <StoreProvider>
            <div className="w-full min-h-[100vh] flex flex-col justify-between">
              {children}
            </div>
            <Toaster />
          </StoreProvider>
        </SessionContext>
      </body>
    </html>
  );
}
